// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(NetpcDbContext))]
    [Migration("20250602121210_categoryModelFix")]
    partial class categoryModelFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Bussiness"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Private"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "School",
                            ParentCategoryId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Boss",
                            ParentCategoryId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Employee",
                            ParentCategoryId = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ContactInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SureName")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateOnly(2000, 1, 1),
                            CategoryId = 1L,
                            Name = "Amadeusz",
                            SureName = "Eusz",
                            email = "amadeusz.eusz@company.com",
                            phoneNumber = "+48717292111"
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateOnly(2005, 2, 2),
                            CategoryId = 4L,
                            Name = "Benedykt",
                            SureName = "Edykt",
                            email = "Bene@gmail.com",
                            phoneNumber = "+48717292222"
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateOnly(1995, 3, 3),
                            CategoryId = 2L,
                            Name = "Cyceron",
                            SureName = "Ron",
                            email = "Cyceron@pg.com",
                            phoneNumber = "+48717292333"
                        });
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.HasOne("backend.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("backend.Models.ContactInfo", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
